version: "3"
services:
  backend:
    image: hemanth0007/event-manager-backend:1
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: ${MONGO_URI}
      SECRET_KEY: ${SECRET_KEY}
      FRONTEND_URL: ${FRONTEND_URL}
      GMAIL: ${GMAIL}
      GMAIL_APP_PASSWORD: ${GMAIL_APP_PASSWORD}

  frontend:
    image: hemanth0007/event-manager-react-image:1
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
