name: Deploy to EC2 via Self-Hosted Runner

on:
  push:
    branches:
      - main

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
  MONGO_URI: ${{ secrets.MONGO_URI }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
  GMAIL: ${{ secrets.GMAIL }}
  GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: hemanth0007/event-manager-frontend:v1.0

      - name: Build and push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: hemanth0007/event-manager-backend:v1.0

  deploy-on-ec2:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Stop and remove existing containers
        run: |
          sudo docker-compose down
          sudo docker-compose rm -f
      - name: Pull Docker images
        run: |
          sudo docker pull hemanth0007/event-manager-frontend:v1.0
          sudo docker pull hemanth0007/event-manager-backend:v1.0
      - name: create .env file
        run: |
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> .env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> .env
          echo "GMAIL=${{ secrets.GMAIL }}" >> .env
          echo "GMAIL_APP_PASSWORD=${{ secrets.GMAIL_APP_PASSWORD }}" >> .env
      - name: Run containers with envs
        run: |
          export REACT_APP_API_URL=$REACT_APP_API_URL
          export MONGO_URI=$MONGO_URI
          export SECRET_KEY=$SECRET_KEY
          export FRONTEND_URL=$FRONTEND_URL
          export GMAIL=$GMAIL
          export GMAIL_APP_PASSWORD=$GMAIL_APP_PASSWORD
          
          sudo docker-compose --env-file .env up -d --force-recreate