name: Deploy to EC2 via Self-Hosted Runner

on:
  push:
    branches:
      - main

env:
  REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
  MONGO_URI: ${{ secrets.MONGO_URI }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
  GMAIL: ${{ secrets.GMAIL }}
  GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: create .env file
        run: |
          echo "REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }}" >> .env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "FRONTEND_URL=${{ secrets.FRONTEND_URL }}" >> .env
          echo "GMAIL=${{ secrets.GMAIL }}" >> .env
          echo "GMAIL_APP_PASSWORD=${{ secrets.GMAIL_APP_PASSWORD }}" >> .env

      - name: Run containers with envs
        run: |
          export REACT_APP_API_URL=$REACT_APP_API_URL
          export MONGO_URI=$MONGO_URI
          export SECRET_KEY=$SECRET_KEY
          export FRONTEND_URL=$FRONTEND_URL
          export GMAIL=$GMAIL
          export GMAIL_APP_PASSWORD=$GMAIL_APP_PASSWORD
          
          sudo docker-compose down
          sudo docker-compose build --no-cache
          sudo docker-compose --env-file .env up -d --force-recreate
